files:
  - source: /.config/*
    translation: /.config/%two_letters_code%/%original_file_name%
    multilingual: 1
  - source: /.github/*
    translation: /.github/%two_letters_code%/%original_file_name%
